package pair_18_package;
/*
 * Assessment Group 18
 * CS12S2
 * Kurt Jayson Zacarias, Justine Gayle Nacional
 * Assignment Module 3
 */
public class FactorNPrime extends javax.swing.JFrame {

    /**
     * Creates new form Factoring
     */
    public FactorNPrime() {
        initComponents();
        inspectButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numTextField = new javax.swing.JTextField();
        primeYN = new javax.swing.JLabel();
        inspectButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        checkButton = new javax.swing.JButton();
        factorsLableFSNUM = new javax.swing.JLabel();
        factorsRadio2 = new javax.swing.JRadioButton();
        factorsRadio3 = new javax.swing.JRadioButton();
        factorsRadio4 = new javax.swing.JRadioButton();
        factorsRadio6 = new javax.swing.JRadioButton();
        factorsLabelLSNUM = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Properties");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Number:");

        jLabel2.setText("Factors:");

        jLabel3.setText("Prime?");

        numTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTextFieldActionPerformed(evt);
            }
        });

        primeYN.setText("N/A");

        inspectButton.setText("Inspect");
        inspectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inspectButtonMouseClicked(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        checkButton.setText("Check");
        checkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkButtonMouseClicked(evt);
            }
        });

        factorsLableFSNUM.setText("N/A");

        factorsRadio2.setText("N/A");

        factorsRadio3.setText("N/A");

        factorsRadio4.setText("N/A");

        factorsRadio6.setText("N/A");

        factorsLabelLSNUM.setText("N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(primeYN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(factorsLableFSNUM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(factorsRadio2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(factorsRadio3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(factorsRadio4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(factorsRadio6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(factorsLabelLSNUM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(inspectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inspectButton)
                    .addComponent(factorsLableFSNUM)
                    .addComponent(factorsRadio2)
                    .addComponent(factorsRadio3)
                    .addComponent(factorsRadio4)
                    .addComponent(factorsRadio6)
                    .addComponent(factorsLabelLSNUM))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(primeYN))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(checkButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void inspectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inspectButtonMouseClicked
        String lV = numTextField.getText();
        int rd = Integer.parseInt(lV);
        if((factorsRadio2.isSelected())&&(rd%2==0)){
            factorsRadio2.setSelected(false);
            factorsRadio2.setText("2 YES");
        }else if((factorsRadio3.isSelected())&&(rd%3==0)){
            factorsRadio3.setSelected(false);
            factorsRadio3.setText("3 YES");
        }else if((factorsRadio4.isSelected())&&(rd%4==0)){
            factorsRadio4.setSelected(false);
            factorsRadio4.setText("4 YES");
        }else if((factorsRadio6.isSelected())&&(rd%6==0)){
            factorsRadio6.setSelected(false);
            factorsRadio6.setText("6 YES");
        }else if((factorsRadio2.isSelected())&&(rd%2!=0)){
            factorsRadio2.setSelected(false);
            factorsRadio2.setText("2 NO");
        }else if((factorsRadio3.isSelected())&&(rd%3!=0)){
            factorsRadio3.setSelected(false);
            factorsRadio3.setText("3 NO");
        }else if((factorsRadio4.isSelected())&&(rd%4!=0)){
            factorsRadio4.setSelected(false);
            factorsRadio4.setText("4 NO");
        }else if((factorsRadio6.isSelected())&&(rd%6!=0)){
            factorsRadio6.setSelected(false);
            factorsRadio6.setText("6 NO");
        }
    }//GEN-LAST:event_inspectButtonMouseClicked

    private void checkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkButtonMouseClicked
        //Prime Button
        String lableValue = numTextField.getText();
        int lbl = Integer.parseInt(lableValue);
        boolean isPrime=true;int rem=0;
        for(int i=2;i<=lbl/2;i++){
            rem=lbl%i;
            if(rem==0){
            isPrime=false;
            break;
            }
        }
        if(isPrime)
            primeYN.setText("Yes");
        else
            primeYN.setText("No");
    }//GEN-LAST:event_checkButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        //clear button
        numTextField.setText("");
        primeYN.setText("N/A");//Prime
        factorsLableFSNUM.setText("N/A");//Factorfs
        factorsLabelLSNUM.setText("N/A");//Factorls
        factorsRadio2.setSelected(false);
        factorsRadio3.setSelected(false);
        factorsRadio4.setSelected(false);
        factorsRadio6.setSelected(false);
        factorsRadio2.setText("N/A");
        factorsRadio3.setText("N/A");
        factorsRadio4.setText("N/A");
        factorsRadio6.setText("N/A");
        inspectButton.setEnabled(false);
    }//GEN-LAST:event_clearButtonMouseClicked

    private void numTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTextFieldActionPerformed
        //Disable and enable the inspect button
        //user needs to press enter after inputting a number to enable the button
        String tfValue = numTextField.getText();
        if(Integer.valueOf(tfValue)>0){
            inspectButton.setEnabled(true);
        }else{
            inspectButton.setEnabled(false);
        }
        //Inspect Button
        int cv=Integer.parseInt(tfValue);
            for(int i=1;i<=Math.sqrt(cv);i++){
                if(cv%i==0){
                    factorsLableFSNUM.setText("1");
                    factorsRadio2.setText(Integer.toString(2));
                    factorsRadio3.setText(Integer.toString(3));
                    factorsRadio4.setText(Integer.toString(4));
                    factorsRadio6.setText(Integer.toString(6));
                    factorsLabelLSNUM.setText(Integer.toString(cv));
            }
        }
    }//GEN-LAST:event_numTextFieldActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactorNPrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactorNPrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactorNPrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactorNPrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactorNPrime().setVisible(true);
                new FactorNPrime().setEnabled(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel factorsLabelLSNUM;
    private javax.swing.JLabel factorsLableFSNUM;
    private javax.swing.JRadioButton factorsRadio2;
    private javax.swing.JRadioButton factorsRadio3;
    private javax.swing.JRadioButton factorsRadio4;
    private javax.swing.JRadioButton factorsRadio6;
    public javax.swing.JButton inspectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField numTextField;
    private javax.swing.JLabel primeYN;
    // End of variables declaration//GEN-END:variables
}
