/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zacarias.convertwords;

/**
 *
 * @author ACER
 */
public class ConvertForm extends javax.swing.JFrame {
    
    /**
     * Creates new form ConvertForm
     */
    public ConvertForm() {
        
        initComponents();
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        xofyLabel = new javax.swing.JLabel();
        wordLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sentenceTextField = new javax.swing.JTextField();
        setButton = new javax.swing.JButton();
        convertedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        prevButton.setText("Previous");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        xofyLabel.setText("0 of 0");

        wordLabel.setText("N/A");

        jLabel2.setText("Sentence");

        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        convertedLabel.setText("N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(xofyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(convertedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sentenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sentenceTextField)
                    .addComponent(setButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordLabel)
                    .addComponent(convertedLabel))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xofyLabel)))
        );

        xofyLabel.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static String toLC;
    public static String repDLCC;
    public static String gS;
    public static int index=0;
    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        gS = sentenceTextField.getText();
        toLC = gS.toLowerCase();
        repDLCC= toLC.replaceAll("[^\\p{Alpha} ]","");
        sentenceTextField.setText(repDLCC.trim());
        //counting Words
        xofyLabel.setText("1 of "+count_Words(repDLCC.trim()));
        //first word appears in the (Word)
        String a[] = repDLCC.split(" ");
        String first = a[0];
        wordLabel.setText("Word: "+first);
        if(charIsVowel(first.charAt(0))){
            convertedLabel.setText("Convert: "+a[0]+"way");
        }
        
        for(;index<first.length();index++){
            if(charIsVowel(first.charAt(index))){
                break;
            }
        }
        String translation = first.substring(index) + first.substring(0, index);
        convertedLabel.setText("Convert: "+translation+"ay");
        xofyLabel.setText(index+" of "+count_Words(repDLCC.trim()));
        nextButton.setEnabled(true);
        prevButton.setEnabled(true);
    }//GEN-LAST:event_setButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        String a[] = repDLCC.trim().split(" ");
        
        if(index==1){
            index = a.length;
        }else if(index<=a.length){
            index--;
        }
        String first = a[index];
        if(charIsVowel(first.charAt(0))){
            convertedLabel.setText("Convert: "+a[0]+"way");
        }
        
        for(;index<first.length();index++){
            if(charIsVowel(first.charAt(index))){
                break;
            }
        }
        String translation = first.substring(index) + first.substring(0, index);
        convertedLabel.setText("Convert: "+translation+"ay");
        wordLabel.setText("Word: "+first);
        xofyLabel.setText(index+" of "+count_Words(repDLCC.trim()));
    }//GEN-LAST:event_prevButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        String a[] = repDLCC.trim().split(" ");
        if(index<a.length){
            index++;
        }else if(index>=a.length){
            index =1;
        }
        String first = a[index];
        if(charIsVowel(first.charAt(0))){
            convertedLabel.setText("Convert: "+a[0]+"way");
        }
        
        for(;index<first.length();index++){
            if(charIsVowel(first.charAt(index))){
                break;
            }
        }
        String translation = first.substring(index) + first.substring(0, index);
        convertedLabel.setText("Convert: "+translation+"ay");
        wordLabel.setText("Word: "+first);
        xofyLabel.setText(index+" of "+count_Words(repDLCC.trim()));
    }//GEN-LAST:event_nextButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel convertedLabel;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton nextButton;
    public javax.swing.JButton prevButton;
    public javax.swing.JTextField sentenceTextField;
    public javax.swing.JButton setButton;
    private javax.swing.JLabel wordLabel;
    public javax.swing.JLabel xofyLabel;
    // End of variables declaration//GEN-END:variables
    public static int count_Words(String str)
    {
       int count = 0;
        if (!(" ".equals(str.substring(0, 1))) || !(" ".equals(str.substring(str.length() - 1))))
        {
            for (int i = 0; i < str.length(); i++)
            {
                if (str.charAt(i) == ' ')
                {
                    count++;
                }
            }
            count = count + 1; 
        }
        return count; 
    }
    public static boolean charIsVowel(char c) {
    char[] vowels = { 'a', 'e', 'i', 'o', 'u' };

    for(char ch : vowels) {
        if(c == ch) {
            return true;
        }
    }

    return false;
    }
}

